[package]
name = "rust-nes"
version = "0.1.0"
authors = ["Artem Artemyev <artem.artemyev@springernature.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.13.0"
png = "0.15.0"
lazy_static = "1.4.0"